### ISSUE TITLE
No route to host after upgrade to 1.4.1

### ISSUE THREAD

**Issue by tobad357** [projectcalico/calico-cni#179]
As discussed on slack
We upgraded from 1.1.0 to 1.4.1 and now don't have any routes to the pods on the nodes.
felix.log doesn't show any errors but does show the following error quite a few times but with different mac addresses

```
2016-09-19 12:49:59,849 [WARNING][69/2] calico.felix.fetcd 1065: Validation failed for endpoint WloadEndpointId<eth0>, treating as missing: Expected labels to be a dict, not None.; '{"state":"active","name":"cali6552efb8b78","mac":"8e:86:7b:38:ce:41","profile_ids":["calico-k8s-network"],"ipv4_nets":["10.240.188.135/32"],"ipv6_nets":[],"labels":null}'
```

We have enabled network policy for the kube apiserver and set the following for the kube-system namespace.

```
kubectl annotate ns kube-system "net.beta.kubernetes.io/network-policy={\"ingress\": {\"isolation\": \"DefaultDeny\"}}"
```

```
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
 name: kube-system-allow-all
spec:
 podSelector: {}
 ingress:
  - {}
```
