### ISSUE TITLE
Expose version via command line

### ISSUE THREAD

**Issue by mzupan** [projectcalico/calico-cni#56]
We bootstrap kubernetes and calico via salt. We do things like this for the `kubectl` app

```
curl -L https://storage.googleapis.com/kubernetes-release/release/v1.1.7/bin/linux/amd64/kubectl -o /usr/bin/kubectl:
  cmd.run:
    - unless: kubectl version | grep Client | grep v1.1.7
    - watch_in:
      - service: kubelet
```

It would be create if the `calico` and `calico-ipam` exposed a way to get the version that is currently installed on the system via like an argument 

```
calico --version
```

or 

```
calico version
```

Thanks!
